<?php
require_once __DIR__.'/../../includes/helpers.php';
require_once __DIR__.'/../../includes/service_client.php';
require_login();
$svc=service('legal');
if(isset($_GET['view_document'])){
    $doc=$svc->documentFile((int)$_GET['view_document']);
    if(!$doc){http_response_code(404);exit('Document not found.');}
    $type=(string)$doc['file_type'];$inline=str_starts_with($type,'image/')||$type==='application/pdf'||$type==='text/plain';
    header('Content-Type: '.$type);header('Content-Length: '.(int)$doc['file_size']);header('X-Content-Type-Options: nosniff');header('Content-Disposition: '.($inline?'inline':'attachment').'; filename="'.str_replace(['\"','\r','\n'],'_',basename((string)$doc['file_name'])).'"');echo $doc['file_data'];exit;
}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$message=$svc->handle((string)($_POST['action']??''),$_POST,current_user());flash('success',$message);}catch(Throwable $e){flash('error','Unable to save record: '.$e->getMessage());}redirect('/modules/legal_compliance/index.php'.(!empty($_POST['focus'])?'#'.rawurlencode((string)$_POST['focus']):''));}
$u=current_user();$reportDate=(string)($_GET['report_date']??'');$showAllReports=isset($_GET['report_all']);$obs=$svc->complianceReports($reportDate,$showAllReports?null:5);
$actions=$svc->actionItems();$audits=$svc->audits();$stats=$svc->stats();$documentRequirements=$svc->documentRequirements();$employeeDocumentRows=$svc->employeeDocumentRows();$documentStats=$svc->documentStats();$selectedEmployee=trim((string)($_GET['employee']??''));$selectedEmployeeDocuments=$selectedEmployee!==''?$svc->employeeDocuments($selectedEmployee):[];$employeeNames=$svc->employeeNames();$auditDate=(string)($_GET['audit_date']??'');$showAllAudit=isset($_GET['audit_all']);$staffAdminAudit=(($u['role']??'')==='Administrator')?service('audit')->latestStaffAdmin($auditDate,$showAllAudit?null:5):[];
page_header('Legal & Compliance','legal');show_flash(); ?>
<div class="gw-breadcrumb"><span>Great Solomon Manpower Services Inc.</span><span>/</span><strong>Legal &amp; Compliance</strong></div>
<section class="gw-hero"><div><div class="eyebrow">MODULE 2</div><h1>Legal &amp; Compliance</h1><p>Record compliance reports, obligations, audits, findings, evidence, corrective actions and review dates while preserving the existing report workflow.</p></div></section>
<section class="gw-quick-actions">
<a href="#compliance-report"><span class="material-symbols-outlined">description</span> Add Compliance Report</a>
<a href="#compliance-obligation"><span class="material-symbols-outlined">event_note</span> Add Obligation</a>
<a href="#compliance-action"><span class="material-symbols-outlined">task_alt</span> Add Corrective Action</a>
<a href="#compliance-audits"><span class="material-symbols-outlined">fact_check</span> Compliance Audits</a>
<a href="#compliance-reports"><span class="material-symbols-outlined">list_alt</span> Compliance Reports</a>
<a href="#employee-documents"><span class="material-symbols-outlined">folder_shared</span> Employee Documents</a>
</section>
<section class="gw-stats">
<div class="gw-stat"><span class="gw-stat-label">Compliance Records</span><div class="gw-stat-value"><?=e($stats['obligations'])?></div><div class="gw-stat-meta">Reports &amp; obligations</div></div>
<div class="gw-stat"><span class="gw-stat-label">Overdue</span><div class="gw-stat-value"><?=e($stats['overdue'])?></div><div class="gw-stat-meta warning">Needs review</div></div>
<div class="gw-stat"><span class="gw-stat-label">Audits</span><div class="gw-stat-value"><?=e($stats['audits'])?></div><div class="gw-stat-meta">Scheduled &amp; completed</div></div>
<div class="gw-stat"><span class="gw-stat-label">Due Actions</span><div class="gw-stat-value"><?=e($stats['open_actions'])?></div><div class="gw-stat-meta warning">Open / in progress</div></div>
<div class="gw-stat"><span class="gw-stat-label">Employee Documents</span><div class="gw-stat-value"><?=e($documentStats['documents'])?></div><div class="gw-stat-meta"><?=e($documentStats['verified'])?> verified / <?=e($documentStats['pending'])?> pending</div></div>
<div class="gw-stat"><span class="gw-stat-label">Expired Documents</span><div class="gw-stat-value"><?=e($documentStats['expired'])?></div><div class="gw-stat-meta warning">Requires review</div></div>
</section>

<section class="gw-panel" id="employee-documents" style="margin-top:20px"><div class="gw-panel-head"><div><h2>Employee Legal &amp; Compliance Documents</h2><span>Employees are drawn from Health, Safety &amp; Welfare records. Upload, view, verify and monitor recruitment/deployment documents without changing the existing employee records.</span></div><span class="material-symbols-outlined">folder_shared</span></div>
<div class="record-form" style="margin:18px"><div class="gw-panel-head"><h2>Add / Upload Employee Document</h2><span>Keep supporting records with the employee compliance file</span></div>
<form method="post" enctype="multipart/form-data"><?=csrf_field()?><input type="hidden" name="action" value="upload_employee_document"><input type="hidden" name="focus" value="employee-documents">
<div class="form-grid">
<div><label>Employee</label><select name="employee_name" required><option value="">Select employee</option><?php foreach($employeeNames as $name):?><option value="<?=e($name)?>" <?=($selectedEmployee===$name?'selected':'')?>><?=e($name)?></option><?php endforeach;?></select></div>
<div><label>Employee ID</label><input name="employee_id" placeholder="Optional reference"></div>
<div><label>Document Type</label><select name="requirement_id" id="documentRequirementSelect"><option value="">Custom / select category below</option><?php foreach($documentRequirements as $r):?><option value="<?=$r['id']?>" data-category="<?=e($r['category'])?>"><?=e($r['document_name'])?><?=((int)$r['required_for_recruitment']===1?' — Required':'')?></option><?php endforeach;?></select></div>
<div><label>Document Name</label><input name="document_name" required placeholder="e.g. Passport, Contract, Medical Certificate"></div>
<div><label>Category</label><input name="category" required placeholder="Identity, Health & Welfare, Compliance..."></div>
<div><label>Document / Certificate No.</label><input name="document_number"></div>
<div><label>Issued Date</label><input type="date" name="issued_date"></div>
<div><label>Expiry Date</label><input type="date" name="expiry_date"></div>
<div><label>Review Status</label><select name="status"><option>Pending Review</option><option>Uploaded</option><option>Verified</option><option>Expired</option><option>Rejected</option></select></div>
<div class="full"><label>Notes</label><textarea name="notes" placeholder="Verification notes, issuing authority, client requirement, or other relevant information"></textarea></div>
<div class="full"><label>Document File</label><input type="file" name="employee_document" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx,.txt" required><small>Maximum 25 MB. PDF, image, Word, Excel and TXT files are supported.</small></div>
</div><div class="record-actions"><button class="gw-btn primary"><span class="material-symbols-outlined">upload_file</span> Upload Document</button></div></form></div>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Employee</th><th>Department / Position</th><th>Document Coverage</th><th>Verified</th><th>Pending</th><th>Expired</th><th></th></tr></thead><tbody><?php foreach($employeeDocumentRows as $er):?><tr><td><strong><?=e($er['employee_name'])?></strong><br><small><?=e($er['employee_id']??'')?></small></td><td><?=e(($er['department']??'—').' / '.($er['position_title']??'—'))?></td><td><?=e($er['uploaded_documents'])?> uploaded / <?=e($er['required_documents'])?> recruitment-required</td><td><?=e($er['verified_documents'])?></td><td><?=e($er['pending_documents'])?></td><td><?=e($er['expired_documents'])?></td><td><a class="gw-btn secondary" href="<?=e(url('/modules/legal_compliance/index.php?employee='.rawurlencode($er['employee_name'])))?>#employee-documents">View Documents</a></td></tr><?php endforeach;if(!$employeeDocumentRows):?><tr><td colspan="7" class="empty">No employees have been recorded in Health, Safety &amp; Welfare yet.</td></tr><?php endif;?></tbody></table></div>
<?php if($selectedEmployee!==''):?><div class="record-form" style="margin:18px"><div class="gw-panel-head"><div><h2><?=e($selectedEmployee)?> — Document File</h2><span>Recruitment, health, safety, welfare, deployment and compliance supporting documents</span></div><a class="gw-btn secondary" href="<?=e(url('/modules/legal_compliance/index.php#employee-documents'))?>">Close</a></div>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Document</th><th>Category</th><th>Reference</th><th>Expiry</th><th>Status</th><th>File</th><th>Action</th></tr></thead><tbody><?php foreach($selectedEmployeeDocuments as $d):?><tr><td><strong><?=e($d['document_name'])?></strong><br><small><?=e($d['file_name'])?></small></td><td><?=e($d['category'])?></td><td><?=e($d['document_number']??'—')?></td><td><?=e($d['expiry_date']??'—')?></td><td><?=e($d['status'])?></td><td><?=e(number_format(((int)$d['file_size'])/1024,1))?> KB</td><td><a class="gw-btn secondary" target="_blank" rel="noopener" href="<?=e(url('/modules/legal_compliance/index.php?view_document='.(int)$d['id']))?>">View</a><details class="document-update-details"><summary class="table-action"><span class="material-symbols-outlined">edit</span><span>Update</span></summary><form method="post" style="min-width:260px;padding-top:10px"><?=csrf_field()?><input type="hidden" name="action" value="update_employee_document"><input type="hidden" name="id" value="<?=$d['id']?>"><input type="hidden" name="focus" value="employee-documents"><label>Status</label><select name="status"><?php foreach(['Uploaded','Pending Review','Verified','Expired','Rejected'] as $st):?><option <?=($d['status']===$st?'selected':'')?>><?=e($st)?></option><?php endforeach;?></select><label>Document / Certificate No.</label><input name="document_number" value="<?=e($d['document_number']??'')?>"><label>Expiry Date</label><input type="date" name="expiry_date" value="<?=e($d['expiry_date']??'')?>"><label>Notes</label><textarea name="notes"><?=e($d['notes']??'')?></textarea><button class="gw-btn primary" style="margin-top:8px">Save</button></form></details><form method="post" onsubmit="return confirm('Archive this employee document?')" style="margin-top:6px"><?=csrf_field()?><input type="hidden" name="action" value="delete_employee_document"><input type="hidden" name="id" value="<?=$d['id']?>"><input type="hidden" name="focus" value="employee-documents"><button class="gw-btn btn-danger">Archive</button></form></td></tr><?php endforeach;if(!$selectedEmployeeDocuments):?><tr><td colspan="7" class="empty">No documents uploaded for this employee yet.</td></tr><?php endif;?></tbody></table></div></div><?php endif;?>
<div class="record-form recruitment-requirements" style="margin:18px"><details class="requirements-dropdown" open>
<summary><div><strong>Recruitment Agency Document Requirements</strong><span>Reference checklist for recruitment, placement, welfare, safety, deployment and legal compliance.</span></div><span class="material-symbols-outlined" aria-hidden="true">expand_more</span></summary>
<div class="requirements-scroll" aria-label="Recruitment agency document requirements">
<?php foreach($documentRequirements as $r):?>
<div class="requirement-row">
  <div class="requirement-main"><strong><?=e($r['document_name'])?></strong><span><?=e($r['category'])?></span></div>
  <div class="requirement-description"><?=e($r['description'])?></div>
  <div class="requirement-meta"><span class="requirement-pill"><?=((int)$r['required_for_recruitment']===1?'Required':'As applicable')?></span><span><?=((int)$r['requires_expiry']===1?'Monitor expiry':'No routine expiry')?></span></div>
</div>
<?php endforeach;?>
</div>
</details></div>
</section>
<script>
document.addEventListener('DOMContentLoaded',function(){const sel=document.getElementById('documentRequirementSelect');if(!sel)return;const form=sel.closest('form');const name=form.querySelector('input[name="document_name"]');const cat=form.querySelector('input[name="category"]');sel.addEventListener('change',function(){const opt=sel.options[sel.selectedIndex];if(sel.value){name.value=opt.textContent.replace(/\s+—\s+Required$/,'');cat.value=opt.dataset.category||'';}});});
</script>
<section class="record-form" id="compliance-report"><div class="gw-panel-head"><h2>Add Compliance Report</h2><span>Database-backed report workflow</span></div>
<form method="post"><?=csrf_field()?><input type="hidden" name="action" value="add_report"><input type="hidden" name="focus" value="compliance-reports">
<div class="form-grid">
<div><label>Name</label><input name="report_name" required></div><div><label>Role</label><input name="report_role" required></div><div><label>Contact No.</label><input name="contact_no" required></div>
<div><label>Category</label><input name="category" placeholder="Regulatory, Permit, Internal"></div><div><label>Owner</label><input name="owner"></div><div><label>Due Date</label><input type="date" name="due_date" value="<?=e(date('Y-m-d'))?>" required></div>
<div><label>Priority</label><select name="priority"><option>Low</option><option selected>Medium</option><option>High</option><option>Critical</option></select></div>
<div><label>Status</label><select name="status"><option>Open</option><option>In Progress</option><option selected>Compliant</option><option>Overdue</option></select></div>
<div><label>Regulation / Permit Reference</label><input name="regulation_ref"></div><div><label>Responsible Department</label><input name="responsible_department"></div><div><label>Review Date</label><input type="date" name="review_date"></div><div><label>Evidence Reference</label><input name="evidence_reference"></div>
<div class="full"><label>Compliance / Concern</label><textarea name="compliance_note" required placeholder="Describe the compliance concern, report or observation"></textarea></div>
<div class="full"><label>Finding</label><textarea name="finding"></textarea></div><div class="full"><label>Corrective Action</label><textarea name="corrective_action"></textarea></div>
</div><div class="record-actions"><button class="gw-btn primary">Save Compliance Report</button></div></form></section>

<section class="record-form" id="compliance-obligation"><div class="gw-panel-head"><h2>Compliance Obligation</h2><span>Track recurring legal / regulatory requirements</span></div>
<form method="post"><?=csrf_field()?><input type="hidden" name="action" value="add_obligation"><input type="hidden" name="focus" value="compliance-reports">
<div class="form-grid"><div><label>Requirement Title</label><input name="title" required></div><div><label>Category</label><input name="category"></div><div><label>Owner</label><input name="owner"></div><div><label>Due Date</label><input type="date" name="due_date" required></div><div><label>Priority</label><select name="priority"><option>Low</option><option selected>Medium</option><option>High</option><option>Critical</option></select></div><div><label>Status</label><select name="status"><option>Open</option><option>In Progress</option><option>Compliant</option><option>Overdue</option></select></div><div><label>Regulation Reference</label><input name="regulation_ref"></div><div><label>Responsible Department</label><input name="responsible_department"></div><div><label>Review Date</label><input type="date" name="review_date"></div><div><label>Evidence Reference</label><input name="evidence_reference"></div><div class="full"><label>Finding</label><textarea name="finding"></textarea></div><div class="full"><label>Corrective Action</label><textarea name="corrective_action"></textarea></div></div>
<div class="record-actions"><button class="gw-btn primary">Save Obligation</button></div></form></section>

<section class="gw-panel" id="compliance-reports" style="margin-top:20px"><div class="gw-panel-head"><div><h2>Compliance Reports &amp; Obligations</h2><span><?= $showAllReports?'Showing all matching records':'Showing the latest 5 records' ?><?= $reportDate?' for '.e($reportDate):'' ?></span></div><span class="material-symbols-outlined">manage_search</span></div>
<form method="get" class="date-filter" style="padding:0 18px 14px;justify-content:flex-end"><span class="dashboard-date-filter-label"><span class="material-symbols-outlined">filter_alt</span>Report date</span><input type="date" name="report_date" value="<?=e($reportDate)?>"><button class="gw-btn secondary">Filter</button><?php if($reportDate):?><a class="gw-btn secondary" href="<?=e(url('/modules/legal_compliance/index.php'))?>#compliance-reports">Clear</a><?php endif;?><?php if($showAllReports):?><a class="gw-btn secondary" href="<?=e(url('/modules/legal_compliance/index.php'.($reportDate?'?report_date='.rawurlencode($reportDate):'')))?>#compliance-reports">Show latest 5</a><?php else:?><a class="gw-btn primary" href="<?=e(url('/modules/legal_compliance/index.php?report_all=1'.($reportDate?'&report_date='.rawurlencode($reportDate):'')))?>#compliance-reports">See all compliance reports</a><?php endif;?></form>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Report / Requirement</th><th>Owner</th><th>Due</th><th>Priority</th><th>Status</th><th>Finding / Compliance</th><th></th></tr></thead><tbody><?php foreach($obs as $r):?><tr><td><strong><?=e($r['report_name']??$r['title'])?></strong><br><small><?=e($r['regulation_ref']??'')?></small></td><td><?=e($r['owner']??$r['report_role']??'—')?></td><td><?=e($r['due_date']??'—')?><br><small>Review: <?=e($r['review_date']??'—')?></small></td><td><span class="ui-status priority-<?=strtolower(e($r['priority']??'medium'))?>"><?=e($r['priority']??'—')?></span></td><td><span class="ui-status status-<?=strtolower(str_replace(' ','-',e($r['status']??'')))?>"><?=e($r['status']??'—')?></span></td><td><?=nl2br(e($r['finding']??$r['compliance_note']??''))?></td><td><details><summary class="table-action"><span class="material-symbols-outlined">edit</span><span>Update</span></summary><form method="post" style="min-width:260px;padding-top:10px"><?=csrf_field()?><input type="hidden" name="action" value="update_compliance"><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="focus" value="compliance-reports"><label>Status</label><select name="status"><?php foreach(['Open','In Progress','Compliant','Overdue'] as $s):?><option <?=($r['status']===$s?'selected':'')?>><?=e($s)?></option><?php endforeach;?></select><label>Priority</label><select name="priority"><?php foreach(['Low','Medium','High','Critical'] as $s):?><option <?=($r['priority']===$s?'selected':'')?>><?=e($s)?></option><?php endforeach;?></select><label>Evidence Reference</label><input name="evidence_reference" value="<?=e($r['evidence_reference']??'')?>"><label>Review Date</label><input type="date" name="review_date" value="<?=e($r['review_date']??'')?>"><label>Finding</label><textarea name="finding"><?=e($r['finding']??'')?></textarea><label>Corrective Action</label><textarea name="corrective_action"><?=e($r['corrective_action']??'')?></textarea><button class="gw-btn primary" style="margin-top:8px">Save Update</button></form></details><form method="post" onsubmit="return confirm('Archive this compliance record?')" style="margin-top:6px"><?=csrf_field()?><input type="hidden" name="action" value="delete_report"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="gw-btn btn-danger">Archive</button></form></td></tr><?php endforeach;if(!$obs):?><tr><td colspan="7" class="empty">No compliance reports recorded.</td></tr><?php endif;?></tbody></table></div></section>

<section class="record-form" id="compliance-action"><div class="gw-panel-head"><h2>Corrective / Preventive Action</h2><span>Assign and close compliance actions</span></div>
<form method="post"><?=csrf_field()?><input type="hidden" name="action" value="add_action_item"><input type="hidden" name="focus" value="compliance-action">
<div class="form-grid"><div><label>Compliance Record</label><select name="compliance_id" required><option value="">Select record</option><?php foreach($svc->complianceReports('',null) as $c):?><option value="<?=$c['id']?>"><?=e(($c['report_name']??$c['title']).' — #'.$c['id'])?></option><?php endforeach;?></select></div><div><label>Owner</label><input name="owner"></div><div><label>Due Date</label><input type="date" name="due_date"></div><div><label>Status</label><select name="status"><option>Open</option><option>In Progress</option><option>Completed</option><option>Cancelled</option></select></div><div class="full"><label>Action</label><textarea name="action_text" required></textarea></div><div class="full"><label>Completion Notes</label><textarea name="completion_notes"></textarea></div></div>
<div class="record-actions"><button class="gw-btn primary">Save Action Item</button></div></form></section>

<section class="gw-panel" style="margin-top:20px"><div class="gw-panel-head"><div><h2>Compliance Action Items</h2><span>Corrective and preventive actions</span></div><span class="material-symbols-outlined">task_alt</span></div>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Compliance</th><th>Action</th><th>Owner</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($actions as $a):?><tr><td><?=e($a['compliance_title'])?></td><td><?=nl2br(e($a['action_text']))?></td><td><?=e($a['owner'])?></td><td><?=e($a['due_date']??'—')?></td><td><?=e($a['status'])?></td><td><?php if($a['status']!=='Completed'):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="update_action_item"><input type="hidden" name="id" value="<?=$a['id']?>"><input type="hidden" name="status" value="Completed"><button class="gw-btn secondary">Complete</button></form><?php endif;?></td></tr><?php endforeach;if(!$actions):?><tr><td colspan="6" class="empty">No compliance action items recorded.</td></tr><?php endif;?></tbody></table></div></section>

<section class="record-form" id="compliance-audits"><div class="gw-panel-head"><h2>Compliance Audit</h2><span>Schedule and document audit findings</span></div>
<form method="post"><?=csrf_field()?><input type="hidden" name="action" value="add_audit"><input type="hidden" name="focus" value="compliance-audits"><div class="form-grid"><div><label>Audit Title</label><input name="title" required></div><div><label>Audit Date</label><input type="date" name="audit_date" required></div><div><label>Auditor</label><input name="auditor"></div><div><label>Status</label><select name="status"><option>Scheduled</option><option>In Progress</option><option>Completed</option><option>Closed</option></select></div><div class="full"><label>Findings</label><textarea name="findings"></textarea></div></div><div class="record-actions"><button class="gw-btn primary">Save Audit</button></div></form>
<div class="table-wrap" style="margin-top:18px"><table class="data-table"><thead><tr><th>Audit</th><th>Date</th><th>Auditor</th><th>Status</th><th>Findings</th></tr></thead><tbody><?php foreach($audits as $a):?><tr><td><?=e($a['title'])?></td><td><?=e($a['audit_date'])?></td><td><?=e($a['auditor'])?></td><td><?=e($a['status'])?></td><td><?=nl2br(e($a['findings']))?></td></tr><?php endforeach;if(!$audits):?><tr><td colspan="5" class="empty">No compliance audits recorded.</td></tr><?php endif;?></tbody></table></div></section>

<?php if (($u['role']??'')==='Administrator'): ?>
<section class="gw-panel" id="staff-admin-audit-trail" style="margin-top:20px"><div class="gw-panel-head"><div><h2>Staff &amp; Admin Audit Trail</h2><span><?= $showAllAudit?'Showing all matching audit records':'Showing the latest 5 audit records' ?><?= $auditDate?' for '.e($auditDate):'' ?></span></div><span class="material-symbols-outlined">manage_search</span></div>
<form method="get" class="date-filter" style="padding:0 18px 14px;justify-content:flex-end"><span class="dashboard-date-filter-label"><span class="material-symbols-outlined">filter_alt</span>Audit date</span><input type="date" name="audit_date" value="<?=e($auditDate)?>"><button class="gw-btn secondary">Filter</button><?php if($auditDate):?><a class="gw-btn secondary" href="<?=e(url('/modules/legal_compliance/index.php'))?>#staff-admin-audit-trail">Clear</a><?php endif;?><?php if($showAllAudit):?><a class="gw-btn secondary" href="<?=e(url('/modules/legal_compliance/index.php'.($auditDate?'?audit_date='.rawurlencode($auditDate):'')))?>#staff-admin-audit-trail">Show latest 5</a><?php else:?><a class="gw-btn primary" href="<?=e(url('/modules/legal_compliance/index.php?audit_all=1'.($auditDate?'&audit_date='.rawurlencode($auditDate):'')))?>#staff-admin-audit-trail">See all audit trails</a><?php endif;?></form>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Gmail</th><th>Role</th><th>Module</th><th>Action</th><th>Details</th><th>Date &amp; Time</th></tr></thead><tbody><?php foreach($staffAdminAudit as $a):?><tr><td><?=e($a['name'])?></td><td><?=e($a['email'])?></td><td><?=e($a['role'])?></td><td><?=e($a['module'])?></td><td><?=e($a['action'])?></td><td><?=e($a['details'])?></td><td><?=e($a['created_at'])?></td></tr><?php endforeach;if(!$staffAdminAudit):?><tr><td colspan="7" class="empty">No staff or administrator audit records match the selected filter.</td></tr><?php endif;?></tbody></table></div></section>
<?php endif; ?>
<?php page_footer(); ?>
